Fixing input files for genotyping
biopet/biopet pull request #106
Opened 2017-05-04 10:48 UTC by ffinfo

2017-05-05 09:04 UTC, rhpvorderman requested changes

2017-05-05 09:04 UTC, rhpvorderman commented on shiva/src/main/scala/nl/lumc/sasc/biopet/pipelines/shiva/variantcallers/HaplotypeCallerGvcf.scala
> +    genotypeGvcfs.namePrefix = s"$namePrefix.$name"
namePrefix is defined as prefix+name ? Wouldn't the variable than better be called genotpeGcvfs.nameWithPrefix?

2017-05-08 07:12 UTC, ffinfo commented on shiva/src/main/scala/nl/lumc/sasc/biopet/pipelines/shiva/variantcallers/HaplotypeCallerGvcf.scala
> +    genotypeGvcfs.namePrefix = s"$namePrefix.$name"
Not directly. This name prefix is for genotypeGvcfs, the other is from HaplotypecallerGvcf. Only in HaolotpecallerGvcf I do set the namePrefix of GenotypeGvcfs

2017-05-09 09:13 UTC, rhpvorderman approved these changes

2017-05-09 09:14 UTC, merged