Tarmac plotting
biopet/biopet pull request #112
Opened 2017-05-16 09:09 UTC by sndrtj

2017-05-16 10:09 UTC, ffinfo requested changes

2017-05-16 10:09 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    val bgzip = new Bgzip(this)
Is it possible to combine the Sort job and the Bgzip job?

2017-05-16 10:09 UTC, ffinfo commented on tarmac/src/main/resources/nl/lumc/sasc/biopet/pipelines/tarmac/scripts/tarmac_plot.py
> +def plot_call(chrom, start, end, whandle, xhandle, shandle, margin, output_loc):
Is this plot somehow tested? If not this should be the next task in functional tests

2017-05-16 10:09 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/scripts/TarmacPlot.scala
> +}
It look like the new style reformatter is not in there yet. Could you update this branch to the latest develop? Or first update `feature-tarmac-pipeline` branch for this.

2017-05-16 10:09 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +        add(pipeJob)
You can also write this as add(pipeJob, sort.tabixJob)

2017-05-17 11:35 UTC, sndrtj commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    val bgzip = new Bgzip(this)
This is done in all cases this function is called. The reason not do this in this function is that `pipeJobs` in a `BiopetFifoPipe` is only populated _after_ its `beforeGraph` is called, and I want to access its constituent jobs before that time.

2017-05-17 11:38 UTC, sndrtj commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +        add(pipeJob)
Fixed

2017-05-17 11:38 UTC, sndrtj commented on tarmac/src/main/resources/nl/lumc/sasc/biopet/pipelines/tarmac/scripts/tarmac_plot.py
> +def plot_call(chrom, start, end, whandle, xhandle, shandle, margin, output_loc):
Yes, that's the next step.

2017-05-17 11:38 UTC, sndrtj commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/scripts/TarmacPlot.scala
> +}
Done

2017-05-23 17:54 UTC, ffinfo approved these changes

2017-05-23 17:55 UTC, merged