Refactor delly
biopet/biopet pull request #115
Opened 2017-05-17 07:31 UTC by johnmous

2017-05-17 14:32 UTC, johnmous commented
@ffinfo I see this test failure: Unable to delete directory /tmp/1495030236169-0/.log/test/config.
from nl.lumc.sasc.biopet.pipelines.flexiprep.FlexiprepTest.removeTempOutputDir(FlexiprepTest.scala:114)

and I dont see where it comes from (didnt touch anything in flexiprep)

2017-05-18 10:43 UTC, ffinfo requested changes
Just a few things that need changes but in general it look fine. I still want to be sure the functional test does work on this.

2017-05-18 10:43 UTC, ffinfo commented on shiva/src/main/scala/nl/lumc/sasc/biopet/pipelines/shiva/svcallers/Delly.scala
> +        delly.outputbcf = new File(dellyDir, sample + ".delly.tra.bcf")
why bcf is used here? it's more use friendly to use vcf instead

2017-05-18 10:43 UTC, ffinfo commented on shiva/src/test/scala/nl/lumc/sasc/biopet/pipelines/shiva/ShivaSvCallingTest.scala
> +                                                                                                    0))
This a bit ugly auto formatted. This has todo with the max line length. If you rewrite is like this:
``` scala
pipeline.functions.count(_.isInstanceOf[DellyCallerCall]) shouldBe
  ((if (del) 1 else 0) + (if (dup) 1 else 0) + (if (inv) 1 else 0) +
    (if (bnd) 1 else 0) + (if (ins)1 else 0))
```

This way the auto formater does need to use this nasty tricks ;)

2017-05-18 10:43 UTC, ffinfo commented on shiva/src/test/scala/nl/lumc/sasc/biopet/pipelines/shiva/ShivaSvCallingTest.scala
> -    if (!del && !dup && !inv && !tra) intercept[IllegalStateException] {
`tra` is not in there anymore?

2017-05-18 10:43 UTC, ffinfo commented on biopet-extensions/src/main/scala/nl/lumc/sasc/biopet/extensions/delly/DellyCallerCall.scala
> +  def versionRegex = """Delly \(Version: (.*)\)""".r
Can this regex also work on both versions?

2017-05-18 11:36 UTC, johnmous commented on shiva/src/main/scala/nl/lumc/sasc/biopet/pipelines/shiva/svcallers/Delly.scala
> +        delly.outputbcf = new File(dellyDir, sample + ".delly.tra.bcf")
Unfortunately Delly only outputs bcf now

2017-05-18 11:37 UTC, johnmous commented on shiva/src/test/scala/nl/lumc/sasc/biopet/pipelines/shiva/ShivaSvCallingTest.scala
> -    if (!del && !dup && !inv && !tra) intercept[IllegalStateException] {
tra is now renamed to bnd, for breakend

2017-05-18 11:39 UTC, johnmous commented on shiva/src/test/scala/nl/lumc/sasc/biopet/pipelines/shiva/ShivaSvCallingTest.scala
> +                                                                                                    0))
Yep, I noticed that autoformating was doing some nasty things breaking it into too many lines. Is it the module Ruben recently installed? Can we fix this?

2017-05-18 11:40 UTC, johnmous commented on biopet-extensions/src/main/scala/nl/lumc/sasc/biopet/extensions/delly/DellyCallerCall.scala
> +  def versionRegex = """Delly \(Version: (.*)\)""".r
Good point, I will look into it

2017-05-23 14:17 UTC, ffinfo commented
Closing till we got reply from author why variants are missing

2017-05-23 14:17 UTC, closed without merging