add option in flexiprep to downsample input with a fraction
biopet/biopet pull request #127
Opened 2017-05-31 14:40 UTC by sndrtj

2017-06-01 08:26 UTC, ffinfo requested changes

2017-06-01 08:26 UTC, ffinfo commented on flexiprep/src/main/scala/nl/lumc/sasc/biopet/pipelines/flexiprep/QcCommand.scala
> +    case Some(f) if 0.0 < f && f < 1.0 =>
Maybe also add something like this after this case?
``` scala
case Some(f) => 
  Logging.addError("downsample_fraction should be more then 0.0 and lower then 1.0")
```

2017-06-01 08:26 UTC, ffinfo commented on flexiprep/src/main/scala/nl/lumc/sasc/biopet/pipelines/flexiprep/QcCommand.scala
> +        subsample.isIntermediate = true
This is executed inside a pipe so this is redundant

2017-06-01 08:27 UTC, ffinfo commented
An generic note, could you also add this to functional tests in flexiprep?

2017-06-01 11:31 UTC, sndrtj commented on flexiprep/src/main/scala/nl/lumc/sasc/biopet/pipelines/flexiprep/QcCommand.scala
> +    case Some(f) if 0.0 < f && f < 1.0 =>
:+1:

2017-06-06 15:54 UTC, ffinfo approved these changes

2017-06-07 07:26 UTC, merged