added a short text to user documentation
biopet/biopet pull request #14
Opened 2017-01-27 14:16 UTC by akaljuvee

Added a short text to user documentation, it says that it's possible to generate config files with the help of Biopet.

2017-01-30 14:50 UTC, ffinfo requested changes

2017-01-30 14:50 UTC, ffinfo commented on Jenkinsfile
> +            sh 'mkdocs build'
Can this be done with --clean and --strict ? Without this mkdocs will not give a non-0 exitcode and Jenkins will still accept this.

2017-01-30 15:43 UTC, akaljuvee commented on Jenkinsfile
> +            sh 'mkdocs build'
indeed the flag --strict should be present, but this mkdocs isn't consistent - if there's a wrong *.md file written in mkdocs.yml then it's an error, but if there's a mistake in one of the *.md files then it's a warning

2017-01-31 08:12 UTC, ffinfo approved these changes

2017-01-31 09:58 UTC, merged