Fix fastq sync prefixes
biopet/biopet pull request #148
Opened 2017-07-03 13:30 UTC by ffinfo

2017-07-17 08:55 UTC, sndrtj requested changes

2017-07-17 08:55 UTC, sndrtj commented on biopet-tools/src/main/scala/nl/lumc/sasc/biopet/tools/FastqSync.scala
> +  def findR1R2Subfixes(fastqR1: File, fastqR2: File): (String, String) = {
Could you please add a docstring as to what this does.

2017-07-17 08:55 UTC, sndrtj commented on biopet-tools/src/main/scala/nl/lumc/sasc/biopet/tools/FastqSync.scala
> +    val subFixes = findR1R2Subfixes(commandArgs.refFastq1, commandArgs.refFastq2)
This value does not seem to be used anywhere.

2017-07-18 16:18 UTC, ffinfo commented on biopet-tools/src/main/scala/nl/lumc/sasc/biopet/tools/FastqSync.scala
> +    val subFixes = findR1R2Subfixes(commandArgs.refFastq1, commandArgs.refFastq2)
Good point, something went wrong there

2017-07-18 16:23 UTC, ffinfo commented on biopet-tools/src/main/scala/nl/lumc/sasc/biopet/tools/FastqSync.scala
> +  def findR1R2Subfixes(fastqR1: File, fastqR2: File): (String, String) = {
Added this

2017-07-24 16:14 UTC, merged