First implementation of PIM in biopet
biopet/biopet pull request #150
Opened 2017-07-06 07:51 UTC by ffinfo

2017-07-11 08:39 UTC, bow requested changes

2017-07-11 08:39 UTC, bow commented on biopet-utils/src/main/scala/nl/lumc/sasc/biopet/utils/pim/Pim.scala
> +                nodeType: String)
Aren't `nodeType` or other type arguments better as enums or case classes?

2017-07-11 08:39 UTC, bow commented on biopet-utils/pom.xml
> +            <groupId>com.typesafe.play</groupId>
Isn't the play framework a little too big for just making HTTP calls? AFAIK there are smaller libraries (e.g. [Dispatch](https://dispatchhttp.org/Dispatch.html))

2017-07-11 08:39 UTC, bow commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/pipelinestatus/PipelineStatus.scala
> +      require(pimRunId.isDefined, "Could not auto genrate Pim run ID, please supply --pimRunId")
`s/auto genrate/auto-generate/g`

2017-07-11 08:39 UTC, bow commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/WriteDependencies.scala
> +import akka.actor.ActorSystem
Is the entire akka framework strictly necessary here? We are only doing HTTP calls right?

2017-07-11 08:39 UTC, bow commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/pipelinestatus/Deps.scala
> +  def compressOnType(main: Boolean = false): Map[String, List[String]] = {
In here and other places, Scaladoc should be added.

2017-07-11 08:57 UTC, ffinfo commented on biopet-utils/src/main/scala/nl/lumc/sasc/biopet/utils/pim/Pim.scala
> +                nodeType: String)
as far I know this is a free form

2017-07-11 08:59 UTC, ffinfo commented on biopet-utils/pom.xml
> +            <groupId>com.typesafe.play</groupId>
yes but try reading this ;)
https://www.implicitdef.com/2015/11/19/comparing-scala-http-client-libraries.html

2017-07-11 09:01 UTC, ffinfo commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/pipelinestatus/PipelineStatus.scala
> +      require(pimRunId.isDefined, "Could not auto genrate Pim run ID, please supply --pimRunId")
fixed

2017-07-11 09:03 UTC, ffinfo commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/WriteDependencies.scala
> +import akka.actor.ActorSystem
Yes, this seems like overkill indeed. But also want to see if this framework can be used later to make live reporting while running. Then such a framework is needed anyway

2017-07-11 09:03 UTC, ffinfo commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/pipelinestatus/Deps.scala
> +  def compressOnType(main: Boolean = false): Map[String, List[String]] = {
indeed, will work on that

2017-07-11 10:50 UTC, bow commented on biopet-utils/pom.xml
> +            <groupId>com.typesafe.play</groupId>
That blog post is slightly outdated, I think. Dispatch is still quite maintained (well, a newer version of it): https://github.com/dispatch/reboot. Also, if this is still not suitable, there should be a lot of smaller Java libraries for HTTP clients right? I think there is an Apache project made for this.

2017-07-12 08:03 UTC, ffinfo commented on biopet-utils/pom.xml
> +            <groupId>com.typesafe.play</groupId>
I think I will stay with play for now. I do agree that smaller liraries are nice but seeing the future plan I have the play/akka framework does suit better. I will not have 2 libraries inside biopet that overlap.

2017-07-12 11:30 UTC, bow approved these changes

2017-07-12 11:31 UTC, merged