Fix biopet 607
biopet/biopet pull request #38
Opened 2017-03-20 16:23 UTC by rhpvorderman

Autogenerated some missing documentation.

2017-03-20 17:19 UTC, sndrtj requested changes
Absolutely great idea! :+1: 

I do have some small comments on the scripts. Please check them out :-).

2017-03-20 17:19 UTC, sndrtj commented on biopet-autodoc/synchronize_docs.sh
> +
For some extra checking, you may want set `set -eu` and `set -o pipefail` in the beginning of the script. This makes sure bash ends when it encounters an error or an unset variable.

2017-03-20 17:19 UTC, sndrtj commented on biopet-autodoc/templateparser.py
> +    parser=argparse.ArgumentParser(description="")
The `description` is an optional variable. If you set it to an empty string, you may as well leave it out altogether ;-).

2017-03-20 17:19 UTC, sndrtj commented on biopet-autodoc/templateparser.py
> +    parser.add_argument("-t", type=str, nargs=1, help="Templatefile to be used")
If you don't set `nargs`, accessing this value becomes easier, as you don't have to access a list.

2017-03-20 17:19 UTC, sndrtj commented on biopet-autodoc/templateparser.py
> +    file=open(output_file, "w")
The `seek` call here is unnecessary. Also, if you put this under a context handler, you do not have to manually close the handle.
E.g.:

```
with open(output_file, "w") as output_handle:
    output_handle.write(rendered)
```

2017-03-22 09:14 UTC, rhpvorderman commented
The autodocumentation will be done in another way.

2017-03-22 09:14 UTC, closed without merging