Fix BIOPET-379
biopet/biopet pull request #4
Opened 2017-01-14 13:44 UTC by ffinfo

2017-01-17 12:12 UTC, sndrtj requested changes
I have several comments you may want to look at on this PR.

2017-01-17 12:12 UTC, sndrtj commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/MultiSampleQScript.scala
> +          Logging.addError("libraries is not a map")
This is a somewhat nebulous error message if one is not familiar with the internal structure we use here. Perhaps simply state the contents are wrongly formatted?

2017-01-17 12:12 UTC, sndrtj commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/BiopetQScript.scala
> +  def safeIsDone(function: QFunction): Boolean = {
I would change this function and `safeIsFail` to have type `Option[Boolean]`. You return simply `false` here when the underlying method does not exist, but I believe that's potentially giving a wrong answer. Returning `None` (as in, no boolean exists here) is semantically better, imho.

2017-01-17 12:12 UTC, sndrtj commented on biopet-core/src/test/scala/nl/lumc/sasc/biopet/core/MultiSampleQScriptTest.scala
> +      def summaryFile: File = new File("./summary.json")
If this file gets created during the test, we want to remove it after teardown.

2017-01-17 12:24 UTC, ffinfo commented on biopet-core/src/test/scala/nl/lumc/sasc/biopet/core/MultiSampleQScriptTest.scala
> +      def summaryFile: File = new File("./summary.json")
is does not get created :)

2017-01-17 12:25 UTC, ffinfo commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/BiopetQScript.scala
> +  def safeIsDone(function: QFunction): Boolean = {
maybe indeed a better option

2017-01-17 15:24 UTC, ffinfo commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/MultiSampleQScript.scala
> +          Logging.addError("libraries is not a map")
changed this

2017-01-17 15:24 UTC, ffinfo commented on biopet-core/src/main/scala/nl/lumc/sasc/biopet/core/BiopetQScript.scala
> +  def safeIsDone(function: QFunction): Boolean = {
Changed this

2017-01-18 12:55 UTC, sndrtj approved these changes

2017-01-18 12:55 UTC, merged