address biopet-609, fix broken links, reorganize layout.
biopet/biopet pull request #48
Opened 2017-03-28 20:30 UTC by hailiangmei

2017-03-29 10:21 UTC, hailiangmei commented
deadlink removed. @ffinfo can we merge now?

2017-03-29 11:50 UTC, ffinfo requested changes
Some comments but can you also remove the yamsvp.md file?

2017-03-29 11:50 UTC, ffinfo commented on docs/pipelines/shiva.md
> +* Freebayes
Adding link to the websites of the tools?

2017-03-29 11:50 UTC, ffinfo commented on docs/pipelines/shiva.md
>  *`mapping_to_gears: unmapped` : Unmapped reads after alignment. (default)
For biopet the default is `none`, on shark the default is `all`

2017-03-29 11:50 UTC, ffinfo commented on docs/pipelines/shiva.md
>  At this moment the following variant callers can be used
This should be a table with the following items as config value:
- haplotypecaller_gvcf
- haplotypecaller_allele
- unifiedgenotyper_allele
- unifiedgenotyper
- haplotypecaller
- freebayes
- raw
- bcftools
- bcftools_singlesample
- varscan_cns_singlesample

Currently it's unclear what each config value is for each caller

2017-03-29 19:34 UTC, hailiangmei commented on docs/pipelines/shiva.md
> +* Freebayes
fixed

2017-03-29 19:35 UTC, hailiangmei commented on docs/pipelines/shiva.md
>  *`mapping_to_gears: unmapped` : Unmapped reads after alignment. (default)
fixed.

2017-03-29 19:35 UTC, hailiangmei commented on docs/pipelines/shiva.md
>  At this moment the following variant callers can be used
add one extra column in the config value table. Can you check?

2017-03-30 05:31 UTC, ffinfo commented on docs/pipelines/shiva.md
> +| shiva | dbsnp_vcf | String |  | vcf file of dbsnp records | haplotypecaller, haplotypecaller_gvcf, haplotypecaller_allele, unifiedgenotyper, unifiedgenotyper_allele|
I think this is the wrong line ;)

2017-03-30 13:21 UTC, hailiangmei commented on docs/pipelines/shiva.md
> +| shiva | dbsnp_vcf | String |  | vcf file of dbsnp records | haplotypecaller, haplotypecaller_gvcf, haplotypecaller_allele, unifiedgenotyper, unifiedgenotyper_allele|
can you correct it?

2017-03-31 12:21 UTC, ffinfo approved these changes

2017-03-31 12:22 UTC, merged