Tarmac reference building
biopet/biopet pull request #59
Opened 2017-04-06 15:22 UTC by sndrtj

2017-04-07 09:32 UTC, bow requested changes
Hey @sndrtj,

Looks ok in general, but I see several places that `\/` is filtered then on the subsequent map it is extracted manually. This can be combined to a single operation using `.collect`.

2017-04-07 09:32 UTC, bow commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    val initRefMap = samples map { x => x._2 -> getReferenceSamplesForSample(x._1) }
to make this more readable, you can also pattern match on the tuple directly:
```
val initRefMap = samples.map { case (a, b) => b -> getReferenceSamplesForSample(a) }
```
(of course `a` and `b` should be named appropriately).

2017-04-07 09:32 UTC, bow commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    }
You can shorten this like so:
```
initRefMap.values.collect { case -\/(err) => err }.foreach { Logging.addError }
```

2017-04-07 09:32 UTC, bow commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    val refMap: Map[Sample, Set[Sample]] = initRefMap.filter(_._2.isRight).map { x =>
Similar to the above, I think using `.collect` and pattern matching would make this more clear.

2017-04-07 13:20 UTC, ffinfo requested changes

2017-04-07 13:20 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +      case _            => ;
`;` is redundant

2017-04-07 13:20 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    val refMap: Map[Sample, Set[Sample]] = initRefMap.filter(_._2.isRight).map { x =>
`.map` works here but maybe do is like this:
``` scala
.map { case (key, value) => 
  // your code
}
```

2017-04-07 13:20 UTC, ffinfo commented
I think all test should be unit tested, is there a way to do this already on this branch?

2017-04-10 08:01 UTC, sndrtj commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +      case _            => ;
Compiler gives a warning message if not.

2017-04-11 09:06 UTC, ffinfo approved these changes

2017-04-11 09:06 UTC, merged