Added gcDistribution function.
biopet/biopet pull request #81
Opened 2017-04-18 13:07 UTC by rhpvorderman

2017-04-18 16:08 UTC, ffinfo requested changes

2017-04-18 16:08 UTC, ffinfo commented on flexiprep/src/main/scala/nl/lumc/sasc/biopet/pipelines/flexiprep/Fastqc.scala
> +  def gcDistribution: Option[Map[Int, Double]] = {
Could you add some scaladocs here?

2017-04-20 13:18 UTC, rhpvorderman commented on flexiprep/src/main/scala/nl/lumc/sasc/biopet/pipelines/flexiprep/Fastqc.scala
> +  def gcDistribution: Option[Map[Int, Double]] = {
It is now added.

2017-04-20 13:23 UTC, ffinfo approved these changes

2017-04-25 20:54 UTC, merged