Tarmac z score
biopet/biopet pull request #91
Opened 2017-04-25 10:07 UTC by sndrtj

2017-04-25 11:33 UTC, ffinfo requested changes
Next is functional testing?

2017-04-25 11:33 UTC, ffinfo commented on biopet-extensions/src/main/scala/nl/lumc/sasc/biopet/extensions/bedtools/BedtoolsMerge.scala
> +  var additionalColumns: Option[List[Int]] = None
is it not better to just use `List[Int]` here? When the list is empty nothing needs to be happen

2017-04-25 11:33 UTC, ffinfo commented on biopet-extensions/src/main/scala/nl/lumc/sasc/biopet/extensions/wisecondor/WisecondorZscore.scala
> +  var referenceDictionary: File = _
Is this the same as a dict file or is this something else?

2017-04-25 11:33 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    val wisecondorZJobs = wisecondorRefJobs map {
Making vals for methods inside a method is not really usefull. This is usefull if you want to have access to the jobs output this class but in this way the collections of addAll's a just a bit weird

2017-04-25 11:33 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    addAll(xhmmRefJobs.values.flatMap(_._1))
Since it's inside the same method maybe better to move this to the blocks where they belong to?

2017-04-25 11:33 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +    (reference :: sort :: gzipRef :: tabix :: Nil, refFile)
This should be a FifoPipe, this reduces the complexity of the pipeline a lot

2017-04-25 11:33 UTC, ffinfo commented on tarmac/src/main/scala/nl/lumc/sasc/biopet/pipelines/tarmac/Tarmac.scala
> +  def createXhmmZscore(sample: Sample, referenceMatrix: File): Tuple2[List[QFunction], File] = {
`Tuple2[List[QFunction], File]` is the same as `(List[QFunction], File)`

2017-04-26 11:27 UTC, sndrtj commented on biopet-extensions/src/main/scala/nl/lumc/sasc/biopet/extensions/wisecondor/WisecondorZscore.scala
> +  var referenceDictionary: File = _
No, that is the reference batch file for wisecondor.

2017-05-02 10:38 UTC, ffinfo approved these changes

2017-05-02 10:38 UTC, merged